config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'posts#index'
 match "signout", to: "sessions#destroy", via: [:get, :post]

 get '/baixe-aqui-seu-planner-para-eventos', controller: 'landing', action: "planner"
 get '/baixe-aqui-seu-checklist-para-eventos', controller: 'landing', action: "checklist"
 get '/baixe-aqui-seu-framework-para-eventos', controller: 'landing', action: "framework"
 post '/download/:id', controller: 'landing', action: 'download'
 post '/obrigado-pelo-download', controller: 'landing', action: 'thankyou'
 get '/descubra-quem-e-voce-eventos-empresa', controller: 'landing', action: 'events'
 get '/descubra-qual-tipo-evento-ir-fim-de-semana', controller: 'landing', action: 'events_weekend'

 scope '/admin' do
    get '/', controller: :posts, action: :list, as: :admin
    get '/posts/list', controller: :posts, action: :list

    resources :posts, only: [:new, :edit, :create, :update, :destroy]
    # get '/posts/new', controller: :posts, action: :new
    # get '/posts/edit/:id', controller: :posts, action: :edit, as: 'posts_edit'
    # post '/posts/delete/:id', controller: :posts, action: :destroy, as: 'posts_destroy'
    # post '/posts/create', controller: :posts, action: :create
    # post '/posts/update/:id', controller: :posts , action: :update, as: 'posts_update'
  end


  # Example resource route (maps HTTP verbs to controller actions automatically):
    namespace :posts do
      get '/' , action: :index
      get '/index' , action: :index
      get '/:id', action: :show , as: 'show'
      post '/download/:id', action: :download, as: 'download'
      get '/concluded/:id', action: :concluded, as: 'concluded'
    end

    namespace :users do
      get '/index', action: :index
      get '/new', action: :new
    end

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/post.rb
class Post
  include Mongoid::Document
  include Mongoid::Paperclip
  include Mongoid::Timestamps

  has_mongoid_attached_file  :main_image, styles: { big: "900x900>", medium: "500x500>", thumb: "250x250>", minithumb:  "55x54#" }
  validates_attachment_content_type :main_image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

  field :active, type: Boolean #Indica se esta ativo no sistema
  field :title, type: String        #Titulo do post
  field :description, type: String #Pequena descricao
  field :content, type: String      #Conteudo do post (wysiwyg)
  field :author, type: String       #Autor do post (em mini-site é a empresa)
  field :tags, type: Array            #tags do post (colocadas manualmente)
  field :views, type: Integer       #Numero de visualizacoes

  def self.create params
    post = Post.new

    post.title = params[:title]
    post.content = params[:content]
    post.author = params[:author]
    post.active = params[:active]
    post.description = params[:description]
    post.tags = params[:tags].split(",")
    post.views = 0
    post.main_image = params[:main_image] if params[:main_image]

    post
  end

  def self.update post, params
    post.title = params[:title]
    post.content = params[:content]
    post.author = params[:author]
    post.active = params[:active]
    post.description = params[:description]
    post.tags = params[:tags].split(",")
    post.main_image = params[:main_image] if params[:main_image]

  end

  def tag_list=value
    self.tags = value.split(",")
  end

  def tag_list
    tags.join(",") rescue ""
  end
end

app/controllers/posts_controller.rb
# -*- encoding : utf-8 -*-

class PostsController < ApplicationController
  before_action :set_post, only: [:edit, :update, :destroy]
  before_filter :authorize_admin, only: [:new, :edit, :list, :update, :create, :destroy]

  def index
     if not current_admin_user.nil?
      redirect_to admin_path and return
    end

    @posts = Post.where(active: true).order_by(:created_at.desc)

    respond_to do |format|
      format.html
      format.json { render json: { post: @posts} }
    end
  end

  def show
    @posts = Post.where(active: true).order_by(:views.desc)[0..5]
    @post = Post.find(params[:id])
    @post.views ||= 0
    @post.views += 1
    @post.save!

    respond_to do |format|
      format.html
      format.json { render json: { post: @post } }
    end
  end

  def mini_site

  end

  def list
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to posts_list_path, notice: 'Post criado com sucesso!' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to posts_list_path, notice: 'Post atualizado com sucesso!' }
        format.json { render :list, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
   @post.destroy
   respond_to do |format|
      format.html { redirect_to posts_list_path, notice: "Post removido com sucesso!" }
      format.json { hepost :no_content }
    end
  end

  def download
   @id = params[:id]
   user_params = params[:user]
   @user = User.new
   @user.name = user_params[:name] + " " + user_params[:last_name]
   @user.email = user_params[:email]
   @user.isPJ = user_params[:isPJ]
   @user.password = user_params[:email]
   @user.save!

   respond_to do |format|
        format.html { redirect_to posts_concluded_path(@id) }
        format.json { hepost :no_content }
    end
  end

  def concluded
    @post = Post.find(params[:id])
  end

  def leads_list
    @users = User.all
    respond_to do |format|
      format.csv do
        headers['Content-Disposition'] = "attachment; filename=\"leads-list\""
        headers['Content-Type'] ||= 'text/csv'
      end
    end
  end

  private
  def set_post
      @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:active, :title, :description, :content, :author, :tag_list , :main_image, :pdf_file)
  end

end

app/helpers/posts_helper.rb
module PostsHelper
  def self.similar_posts post
    results = Post.collection.aggregate(
      {
        "$match" => {  tags: { "$in" => post.tags.to_a }, _id: { "$ne" => post.id }, _blog_type: { "$ne" => "mini_site"} },
      },
      { "$unwind" => "$tags" },
      { "$match" => { tags: { "$in" => post.tags.to_a } } },
      { "$group" => { _id: "$_id", matches: { "$sum" =>1 } } },
      { "$sort" => { matches: -1 } },
      { "$limit" => 4 }
    )

    objects = []
    results.map(&:first).map(&:last).each do |result|
      objects << (Post.find result)
    end
    objects
  end

  def self.string_posted_time post
      str = ""
      diff = Time.diff(post.created_at, Time.zone.now)

      p diff
      if  diff[:year] > 0
        str = Time.diff(post.created_at, Time.zone.now, "%y")[:diff]
      elsif  diff[:month] > 0
        str = Time.diff(post.created_at, Time.zone.now, "%M")[:diff]
      elsif  diff[:week] > 0
        str = Time.diff(post.created_at, Time.zone.now, "%w")[:diff]
      elsif  diff[:day] > 0
        str = Time.diff(post.created_at, Time.zone.now, "%d")[:diff]
      elsif  diff[:hour] > 0
        str = Time.diff(post.created_at, Time.zone.now, "%H")[:diff]
      elsif  diff[:minute] > 0
        str = Time.diff(post.created_at, Time.zone.now, "%N")[:diff]
      elsif  diff[:second] > 0
        str = Time.diff(post.created_at, Time.zone.now, "%S")[:diff]
      end
      str
  end

  def self.can_shoot_tags?
    tags = []

    Post.all.each do |tt|
      if tt.tags
        tt.tags.each do |t|
          tags.push(t)
        end
      end
    end

    tags.sort_by{rand}[0..9] if tags.count > 0
  end
end

app/views/posts/_form.html.erb
<%= form_for @post,  html: {class: "form-horizontal", multipart: true} do |f|%>
  <div class="form-group">
    <label for="title">Título  </label>
    <p class="help-block">
        Escreva o título do post
      </p>
      <%= f.text_field :title, class: "form-control", required: true, title:"O título é obrigatório e precisa de no mí­nimo 5 caracteres" %>
  </div>

  <div class="form-group">
    <label for="main_image"> Imagem principal </label>
      <p class="help-block">
        Selecione a imagem principal do post
      </p>
      <%= f.file_field :main_image, accept:"image/jpg,image/jpeg,image/png,image/gif" %>
  </div>

  <div class="form-group">
    <label for="tags"> Tags </label>
      <p class="help-block">
        Tags do post
      </p>
      <%= f.text_field :tag_list, class: "form-control", 'data-role' =>'tagsinput'%>
  </div>

  <div class="form-group">
    <label for="description"> Descrição </label>
      <p class="help-block">
        Pequena descrição do post (resumo)
      </p>
      <%= f.text_field :description, class: "form-control" %>
  </div>

  <div class="form-group">
    <label for="author"> Autor </label>
      <p class="help-block">
        Digite o nome do autor
      </p>
      <%= f.text_field :author, class: "form-control", required: true, title:"O autor do post é obrigatório e precisa de no mí­nimo 5 caracteres" %>
  </div>

  <div class="form-group">
  <label for="content" Text>Texto </label>
    <p class="help-block">
      Digite o conteúdo do seu post
    </p>
    <%= f.text_area :content, class: "tinymce", rows: 40, cols: 120 %>
    <%= tinymce language: "pt_BR" %>
</div>

  <div class="form-group">
      <label>
        <%= f.radio_button :active, true %> Postar agora
      </label>
      <label>
        <%= f.radio_button :active, false %>Postar depois
      </label>
  </div>

  <div class="form-group">
        <%= f.submit (@post.new_record? ? "Criar" : "Atualizar") , class: "btn btn-success" %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1 class="titulo-admin">Editar post</h1>
<%= tinymce_assets %>
<div class="container">
      <div class="row">
	  <%= link_to "Voltar", posts_list_path, class: 'btn btn-default alignright' %>
          <div class="col-sm-12">
            <%= render 'form' %>
          </div>
        </div>
 </div>

app/views/posts/index.html.erb
<% title 'Pense Eventos - O seu blog sobre produção de eventos' %>
<% meta_tag :title,  'Pense Eventos' %>
<% meta_tag :description, 'Seu blog sobre produção de eventos' %>
<% meta_tag :description_twitter, 'Seu blog sobre produção de eventos'  %>
<% meta_tag :url, request.original_url%>
<% meta_tag :image, '/assets/banner_blog_v1.jpg' %>
<div class="container">
		<% @posts.each_with_index do |post,i| %>
                  <div class="row">
      			     <div class="col-sm-12 home-post">
      				<img src="<%= post.main_image(:big) %>" class="img-responsive">
      				<h3 class="post-title"><%= link_to "#{post.title}", posts_show_path(post.id) %></h3>
      				<span class="nome-autor-e-data">Por <%= post.author %> |<%= PostsHelper.string_posted_time post %> atrás </span>
      				<p class="descricao-post"><%= truncate(post.description, length: 440, omission: '...', escape: false) %></p>
      				<%= link_to "Continue lendo", posts_show_path(post.id), class: "btn btn-primary btn-fixo-continuelendo" %>
      			     </div>
                  </div>
		<% end -%>
</div>

<button type="button" style="display: none;" id="hellobar" class="btn btn-primary success" data-toggle="modal" data-target="#myModal"></button>
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
	<div class="modal-dialog" role="document">
      		<div class="modal-content">
        		<div class="modal-header">
          			<button type="button" class="close" data-dismiss="modal"aria-label="Close">
            				<span aria-hidden="true">&times;</span>
          			</button>
          			<h4 class="modal-title" id="myModalLabel">Bem Vindo/a!</h4>
        		</div>
		       <div class="modal-body">
		             <div class="form-group">
		             	Quer lembrar de tudo e ter um passo a passo para organizar um evento de sucesso? <strong>Baixe aqui nosso Checklist!</strong>
		             </div>
		       </div>
        		<div class="modal-footer">
          			<%= link_to "Eu Quero", "/baixe-aqui-seu-checklist-para-eventos",class: "btn btn-primary" %>
          			<button type="button" class="btn btn-default"data-dismiss="modal">Não, Obrigado</button>
        		</div>
      		</div>
	</div>
</div>
<script>
	$(document).ready(function() {
		 setTimeout(function(){
	    		$("#hellobar").click();
    		}, 2000);
	});
</script>

app/views/posts/leads_list.csv.erb
<%- headers = ['Nome', 'Email', 'Tipo', 'IP', 'Data de Cruacao'] -%>
<%= CSV.generate_line headers %>
<%- @users.each do |user| -%>
<%= CSV.generate_line([user.name, user.email, (user.isPJ ? 'B2B' : 'B2C'), user.ip, user.created_at]) -%>
<%- end -%>

app/views/posts/list.html.erb
<h1 class="titulo-admin">Posts publicados/a publicar</h1>
<div class="container">
	<%= link_to 'Sair', destroy_user_session_path, method: :delete, class: "btn btn-default alignright" %>
	<%= link_to "Novo", new_post_path,  class: "btn btn-default" %>
     	<% if @posts.present? %>
       	<div class="row listagemposts">
			<ul>
				<% @posts.each do |post| %>
					<li>
						<%= post.title %> <br />
						<% if post.active %>
							<span class="post-noar">no ar <i class="fa fa-globe" aria-hidden="true"></i></span>
						<% else %>
							<span class="post-airproar">a ir pro ar <i class="fa fa-clock-o" aria-hidden="true"></i></span>
						<% end -%>
						<br />
				             <%= link_to "Editar", edit_post_path(post.id), class: "btn btn-default" %>
				             <%= link_to 'Excluir', post , method: :delete, confirm: "Voce tem certeza?" , class: "btn btn-default"%>
					</li>
				<% end -%>
			</ul>
		</div>
	<% end -%>
</div>

app/views/posts/new.html.erb
<h1 class="titulo-admin">Criar novo post</h1>
<%= tinymce_assets %>
<div class="container">
    	<div class="row">
			<%= link_to "Voltar", posts_list_path, class: 'btn btn-default alignright' %>
      		<div class="col-sm-12">
      			<%= render 'form' %>
      		</div>
      	</div>
 </div>

app/views/posts/show.html.erb
<% title @post.title %>
<% meta_tag :title, @post.title%>
<% meta_tag :description, @post.description%>
<% meta_tag :description_twitter, @post.description[0..130] %>
<% meta_tag :url, request.original_url%>
<% meta_tag :image, @post.main_image.url %>
<div class="container">
	<a href="<%= root_path%>" class="btn btn-voltar"><i class="glyphicon glyphicon-chevron-left"></i>Todos os posts</a>
	<header class="header-post" style="background-image: url('<%= @post.main_image(:medium) if @post.main_image.present?%>')">
		<h1> <%= @post.title %></h1>
		<h2> <%=@post.description %></h2>
		<!--<% @post.tags.each do |tag| %>
			<span class="tag"><%= tag %></span>
		<% end -%>-->
	</header>
	<%= render_shareable buttons: ['twitter', 'facebook', 'google_plus'], :turbolinks => true %>
	<div class="row">
		<div class="col-sm-12 single-post">
  			<%= @post.content.html_safe if @post.content %>
		</div>
		<!--<div class="col-sm-3 sidebar">
			<h4>Posts mais visualizados</h4>
			<ul class="lista-visualizados">
				<% @posts.each do |post| %>
					<li class="post-title"><%= link_to "#{post.title}", posts_show_path(post.id) %></li>
				<% end -%>
			</ul>
			<!--<h4>Tags</h4>
			<% PostsHelper::can_shoot_tags?.each do |tag| %>
	             	<span class="tag"><%= tag %></span>
	            <% end %>
		</div>--><!--/sidebar-->
	</div>
</div>